[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synnet"
version = "0.1.0"
description = "SynNet python version: automated pipeline powered by JCVI + Diamond"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    {name = "Yu-Qian Jiang", email = "yuqian_j@outlook.com"}
]
dependencies = [
    "networkx>=2.8",
]

[project.optional-dependencies]
mcl = ["mcl"]
louvain = ["python-louvain>=0.16"]

[project.scripts]
synnet = "synnet.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
