from datetime import datetime

__author__ = (
    "Yu-Qian Jiang",
)

__copyright__ = f"Copyright (c) 2026-{datetime.now().year}, Yu-Qian Jiang"
__email__ = "yuqian_j@outlook.com"
__license__ = "MIT"
__status__ = "Development"

try:
    from synnet._version import __version__
except ImportError as exc:
    raise ImportError(
        "Failed to find (autogenerated) _version.py"
    ) from exc